
import { GoogleGenAI, Modality } from "@google/genai";
import type { UploadedImage } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
const model = 'gemini-2.5-flash-image';

export const generateFashionModelImage = async (
  userPrompt: string,
  images: UploadedImage[]
): Promise<string> => {
  try {
    const imageParts = images.map(image => ({
      inlineData: {
        data: image.data,
        mimeType: image.mimeType,
      },
    }));

    // The text prompt should instruct the model how to use the images.
    const fullPrompt = {
      text: `Using the following clothing images provided, create a photorealistic image of a fashion model. The model and scene should match this description: "${userPrompt}". The model should be wearing the provided clothing items naturally. Combine all clothing items into a single, cohesive outfit.`
    };

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [...imageParts, fullPrompt],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    // Find the first part that is an image and return its data
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData && part.inlineData.mimeType.startsWith('image/')) {
        return part.inlineData.data;
      }
    }

    throw new Error('No image was generated by the model.');
  } catch (error) {
    console.error('Error generating image with Gemini:', error);
    // Be more specific about API errors if possible
    if (error instanceof Error && error.message.includes('SAFETY')) {
        throw new Error('The request was blocked due to safety settings. Please adjust your prompt or images.');
    }
    throw new Error('Failed to generate image. Please try again.');
  }
};
